/** Curated US companies with public Greenhouse / Lever boards */
export const INTERNSHIP_SOURCE_SEED: Array<{
  company: string;
  company_slug: string;
  ats: "greenhouse" | "lever";
  board_token: string;
  careers_url: string;
}> = [
  { company: "Stripe", company_slug: "stripe", ats: "greenhouse", board_token: "stripe", careers_url: "https://stripe.com/jobs" },
  { company: "Notion", company_slug: "notion", ats: "greenhouse", board_token: "notion", careers_url: "https://www.notion.so/careers" },
  { company: "Figma", company_slug: "figma", ats: "greenhouse", board_token: "figma", careers_url: "https://www.figma.com/careers" },
  { company: "Datadog", company_slug: "datadog", ats: "greenhouse", board_token: "datadog", careers_url: "https://www.datadoghq.com/careers" },
  { company: "Airbnb", company_slug: "airbnb", ats: "greenhouse", board_token: "airbnb", careers_url: "https://careers.airbnb.com" },
  { company: "Discord", company_slug: "discord", ats: "greenhouse", board_token: "discord", careers_url: "https://discord.com/careers" },
  { company: "Brex", company_slug: "brex", ats: "greenhouse", board_token: "brex", careers_url: "https://www.brex.com/careers" },
  { company: "Coinbase", company_slug: "coinbase", ats: "greenhouse", board_token: "coinbase", careers_url: "https://www.coinbase.com/careers" },
  { company: "Databricks", company_slug: "databricks", ats: "greenhouse", board_token: "databricks", careers_url: "https://www.databricks.com/company/careers" },
  { company: "Dropbox", company_slug: "dropbox", ats: "greenhouse", board_token: "dropbox", careers_url: "https://www.dropbox.com/jobs" },
  { company: "HubSpot", company_slug: "hubspot", ats: "greenhouse", board_token: "hubspot", careers_url: "https://www.hubspot.com/careers" },
  { company: "Instacart", company_slug: "instacart", ats: "greenhouse", board_token: "instacart", careers_url: "https://instacart.careers" },
  { company: "Lyft", company_slug: "lyft", ats: "greenhouse", board_token: "lyft", careers_url: "https://www.lyft.com/careers" },
  { company: "MongoDB", company_slug: "mongodb", ats: "greenhouse", board_token: "mongodb", careers_url: "https://www.mongodb.com/careers" },
  { company: "Okta", company_slug: "okta", ats: "greenhouse", board_token: "okta", careers_url: "https://www.okta.com/company/careers" },
  { company: "Palantir", company_slug: "palantir", ats: "greenhouse", board_token: "palantir", careers_url: "https://www.palantir.com/careers" },
  { company: "Pinterest", company_slug: "pinterest", ats: "greenhouse", board_token: "pinterest", careers_url: "https://www.pinterestcareers.com" },
  { company: "Reddit", company_slug: "reddit", ats: "greenhouse", board_token: "reddit", careers_url: "https://www.redditinc.com/careers" },
  { company: "Robinhood", company_slug: "robinhood", ats: "greenhouse", board_token: "robinhood", careers_url: "https://careers.robinhood.com" },
  { company: "Snowflake", company_slug: "snowflake", ats: "greenhouse", board_token: "snowflake", careers_url: "https://careers.snowflake.com" },
  { company: "Square", company_slug: "square", ats: "greenhouse", board_token: "squareup", careers_url: "https://block.xyz/careers" },
  { company: "Twilio", company_slug: "twilio", ats: "greenhouse", board_token: "twilio", careers_url: "https://www.twilio.com/company/jobs" },
  { company: "Unity", company_slug: "unity", ats: "greenhouse", board_token: "unity3d", careers_url: "https://careers.unity.com" },
  { company: "Vercel", company_slug: "vercel", ats: "greenhouse", board_token: "vercel", careers_url: "https://vercel.com/careers" },
  { company: "Webflow", company_slug: "webflow", ats: "greenhouse", board_token: "webflow", careers_url: "https://webflow.com/careers" },
  { company: "Airtable", company_slug: "airtable", ats: "greenhouse", board_token: "airtable", careers_url: "https://airtable.com/careers" },
  { company: "Asana", company_slug: "asana", ats: "greenhouse", board_token: "asana", careers_url: "https://asana.com/jobs" },
  { company: "Canva", company_slug: "canva", ats: "greenhouse", board_token: "canva", careers_url: "https://www.canva.com/careers" },
  { company: "Cloudflare", company_slug: "cloudflare", ats: "greenhouse", board_token: "cloudflare", careers_url: "https://www.cloudflare.com/careers" },
  { company: "Gusto", company_slug: "gusto", ats: "greenhouse", board_token: "gusto", careers_url: "https://gusto.com/careers" },
  { company: "Klaviyo", company_slug: "klaviyo", ats: "greenhouse", board_token: "klaviyo", careers_url: "https://www.klaviyo.com/careers" },
  { company: "Ramp", company_slug: "ramp", ats: "greenhouse", board_token: "ramp", careers_url: "https://ramp.com/careers" },
  { company: "Rippling", company_slug: "rippling", ats: "greenhouse", board_token: "rippling", careers_url: "https://www.rippling.com/careers" },
  { company: "Samsara", company_slug: "samsara", ats: "greenhouse", board_token: "samsara", careers_url: "https://www.samsara.com/company/careers" },
  { company: "Scale AI", company_slug: "scaleai", ats: "greenhouse", board_token: "scaleai", careers_url: "https://scale.com/careers" },
  { company: "Flexport", company_slug: "flexport", ats: "greenhouse", board_token: "flexport", careers_url: "https://www.flexport.com/careers" },
  { company: "Plaid", company_slug: "plaid", ats: "lever", board_token: "plaid", careers_url: "https://plaid.com/careers" },
  { company: "Netflix", company_slug: "netflix", ats: "lever", board_token: "netflix", careers_url: "https://jobs.netflix.com" },
  { company: "Spotify", company_slug: "spotify", ats: "lever", board_token: "spotify", careers_url: "https://www.lifeatspotify.com" },
  { company: "Linear", company_slug: "linear", ats: "lever", board_token: "linear", careers_url: "https://linear.app/careers" },
  { company: "Retool", company_slug: "retool", ats: "lever", board_token: "retool", careers_url: "https://retool.com/careers" },
  { company: "Faire", company_slug: "faire", ats: "lever", board_token: "faire", careers_url: "https://www.faire.com/careers" },
  { company: "Affirm", company_slug: "affirm", ats: "greenhouse", board_token: "affirm", careers_url: "https://www.affirm.com/careers" },
  { company: "Chime", company_slug: "chime", ats: "greenhouse", board_token: "chime", careers_url: "https://www.chime.com/careers" },
  { company: "Duolingo", company_slug: "duolingo", ats: "greenhouse", board_token: "duolingo", careers_url: "https://careers.duolingo.com" },
  { company: "Grammarly", company_slug: "grammarly", ats: "greenhouse", board_token: "grammarly", careers_url: "https://www.grammarly.com/careers" },
  { company: "Hudson River Trading", company_slug: "hrt", ats: "greenhouse", board_token: "hudsonrivertrading", careers_url: "https://www.hudsonrivertrading.com/careers" },
  { company: "Jane Street", company_slug: "janestreet", ats: "greenhouse", board_token: "janestreet", careers_url: "https://www.janestreet.com/join-jane-street" },
];
