/** Curated US companies with public Greenhouse / Lever / Ashby boards */
export const INTERNSHIP_SOURCE_SEED: Array<{
  company: string;
  company_slug: string;
  ats: "greenhouse" | "lever" | "ashby";
  board_token: string;
  careers_url: string;
}> = [
  { company: "Stripe", company_slug: "stripe", ats: "greenhouse", board_token: "stripe", careers_url: "https://stripe.com/jobs" },
  { company: "Figma", company_slug: "figma", ats: "greenhouse", board_token: "figma", careers_url: "https://www.figma.com/careers" },
  { company: "Datadog", company_slug: "datadog", ats: "greenhouse", board_token: "datadog", careers_url: "https://www.datadoghq.com/careers" },
  { company: "Airbnb", company_slug: "airbnb", ats: "greenhouse", board_token: "airbnb", careers_url: "https://careers.airbnb.com" },
  { company: "Discord", company_slug: "discord", ats: "greenhouse", board_token: "discord", careers_url: "https://discord.com/careers" },
  { company: "Brex", company_slug: "brex", ats: "greenhouse", board_token: "brex", careers_url: "https://www.brex.com/careers" },
  { company: "Coinbase", company_slug: "coinbase", ats: "greenhouse", board_token: "coinbase", careers_url: "https://www.coinbase.com/careers" },
  { company: "Databricks", company_slug: "databricks", ats: "greenhouse", board_token: "databricks", careers_url: "https://www.databricks.com/company/careers" },
  { company: "Dropbox", company_slug: "dropbox", ats: "greenhouse", board_token: "dropbox", careers_url: "https://www.dropbox.com/jobs" },
  { company: "HubSpot", company_slug: "hubspot", ats: "greenhouse", board_token: "hubspot", careers_url: "https://www.hubspot.com/careers" },
  { company: "Instacart", company_slug: "instacart", ats: "greenhouse", board_token: "instacart", careers_url: "https://instacart.careers" },
  { company: "Lyft", company_slug: "lyft", ats: "greenhouse", board_token: "lyft", careers_url: "https://www.lyft.com/careers" },
  { company: "MongoDB", company_slug: "mongodb", ats: "greenhouse", board_token: "mongodb", careers_url: "https://www.mongodb.com/careers" },
  { company: "Okta", company_slug: "okta", ats: "greenhouse", board_token: "okta", careers_url: "https://www.okta.com/company/careers" },
  { company: "Pinterest", company_slug: "pinterest", ats: "greenhouse", board_token: "pinterest", careers_url: "https://www.pinterestcareers.com" },
  { company: "Reddit", company_slug: "reddit", ats: "greenhouse", board_token: "reddit", careers_url: "https://www.redditinc.com/careers" },
  { company: "Robinhood", company_slug: "robinhood", ats: "greenhouse", board_token: "robinhood", careers_url: "https://careers.robinhood.com" },
  { company: "Block", company_slug: "block", ats: "greenhouse", board_token: "block", careers_url: "https://block.xyz/careers" },
  { company: "Roblox", company_slug: "roblox", ats: "greenhouse", board_token: "roblox", careers_url: "https://careers.roblox.com" },
  { company: "DoorDash", company_slug: "doordash", ats: "greenhouse", board_token: "doordashusa", careers_url: "https://careers.doordash.com" },
  { company: "Anthropic", company_slug: "anthropic", ats: "greenhouse", board_token: "anthropic", careers_url: "https://www.anthropic.com/careers" },
  { company: "Twilio", company_slug: "twilio", ats: "greenhouse", board_token: "twilio", careers_url: "https://www.twilio.com/company/jobs" },
  { company: "Vercel", company_slug: "vercel", ats: "greenhouse", board_token: "vercel", careers_url: "https://vercel.com/careers" },
  { company: "Webflow", company_slug: "webflow", ats: "greenhouse", board_token: "webflow", careers_url: "https://webflow.com/careers" },
  { company: "Airtable", company_slug: "airtable", ats: "greenhouse", board_token: "airtable", careers_url: "https://airtable.com/careers" },
  { company: "Asana", company_slug: "asana", ats: "greenhouse", board_token: "asana", careers_url: "https://asana.com/jobs" },
  { company: "Cloudflare", company_slug: "cloudflare", ats: "greenhouse", board_token: "cloudflare", careers_url: "https://www.cloudflare.com/careers" },
  { company: "Gusto", company_slug: "gusto", ats: "greenhouse", board_token: "gusto", careers_url: "https://gusto.com/careers" },
  { company: "Klaviyo", company_slug: "klaviyo", ats: "greenhouse", board_token: "klaviyo", careers_url: "https://www.klaviyo.com/careers" },
  { company: "Samsara", company_slug: "samsara", ats: "greenhouse", board_token: "samsara", careers_url: "https://www.samsara.com/company/careers" },
  { company: "Scale AI", company_slug: "scaleai", ats: "greenhouse", board_token: "scaleai", careers_url: "https://scale.com/careers" },
  { company: "Flexport", company_slug: "flexport", ats: "greenhouse", board_token: "flexport", careers_url: "https://www.flexport.com/careers" },
  { company: "Plaid", company_slug: "plaid", ats: "lever", board_token: "plaid", careers_url: "https://plaid.com/careers" },
  { company: "Netflix", company_slug: "netflix", ats: "lever", board_token: "netflix", careers_url: "https://jobs.netflix.com" },
  { company: "Spotify", company_slug: "spotify", ats: "lever", board_token: "spotify", careers_url: "https://www.lifeatspotify.com" },
  { company: "Affirm", company_slug: "affirm", ats: "greenhouse", board_token: "affirm", careers_url: "https://www.affirm.com/careers" },
  { company: "Chime", company_slug: "chime", ats: "greenhouse", board_token: "chime", careers_url: "https://www.chime.com/careers" },
  { company: "Duolingo", company_slug: "duolingo", ats: "greenhouse", board_token: "duolingo", careers_url: "https://careers.duolingo.com" },
  { company: "Jane Street", company_slug: "janestreet", ats: "greenhouse", board_token: "janestreet", careers_url: "https://www.janestreet.com/join-jane-street" },
  { company: "Palantir", company_slug: "palantir", ats: "lever", board_token: "palantir", careers_url: "https://www.palantir.com/careers" },
  { company: "Verkada", company_slug: "verkada", ats: "greenhouse", board_token: "verkada", careers_url: "https://www.verkada.com/careers" },
  { company: "Zscaler", company_slug: "zscaler", ats: "greenhouse", board_token: "zscaler", careers_url: "https://www.zscaler.com/careers" },
  { company: "Labelbox", company_slug: "labelbox", ats: "greenhouse", board_token: "labelbox", careers_url: "https://labelbox.com/careers" },
  { company: "Rubrik", company_slug: "rubrik", ats: "greenhouse", board_token: "rubrik", careers_url: "https://www.rubrik.com/company/careers" },
  { company: "Epic Games", company_slug: "epicgames", ats: "greenhouse", board_token: "epicgames", careers_url: "https://www.epicgames.com/site/careers" },
  { company: "SpaceX", company_slug: "spacex", ats: "greenhouse", board_token: "spacex", careers_url: "https://www.spacex.com/careers" },
  { company: "Rocket Lab", company_slug: "rocketlab", ats: "greenhouse", board_token: "rocketlab", careers_url: "https://www.rocketlabusa.com/careers" },
  { company: "Anduril", company_slug: "anduril", ats: "greenhouse", board_token: "andurilindustries", careers_url: "https://www.anduril.com/careers" },
  { company: "Nuro", company_slug: "nuro", ats: "greenhouse", board_token: "nuro", careers_url: "https://www.nuro.ai/careers" },
  { company: "Gemini", company_slug: "gemini", ats: "greenhouse", board_token: "gemini", careers_url: "https://www.gemini.com/careers" },
  { company: "1Password", company_slug: "1password", ats: "ashby", board_token: "1password", careers_url: "https://1password.com/careers" },
  { company: "Skydio", company_slug: "skydio", ats: "ashby", board_token: "skydio", careers_url: "https://www.skydio.com/careers" },
  { company: "Cohere", company_slug: "cohere", ats: "ashby", board_token: "cohere", careers_url: "https://cohere.com/careers" },
  { company: "Snowflake", company_slug: "snowflake", ats: "ashby", board_token: "snowflake", careers_url: "https://careers.snowflake.com" },
  { company: "Ramp", company_slug: "ramp", ats: "ashby", board_token: "ramp", careers_url: "https://ramp.com/careers" },
  { company: "Notion", company_slug: "notion", ats: "ashby", board_token: "notion", careers_url: "https://www.notion.so/careers" },
  { company: "Replit", company_slug: "replit", ats: "ashby", board_token: "replit", careers_url: "https://replit.com/careers" },
  { company: "Walleye Capital", company_slug: "walleyecapital", ats: "greenhouse", board_token: "walleyecapital-external-students", careers_url: "https://www.walleyecapital.com/careers" },
  { company: "Aquatic Capital Management", company_slug: "aquaticcapital", ats: "greenhouse", board_token: "aquaticcapitalmanagement", careers_url: "https://www.aquatic.com/careers" },
  { company: "Optiver", company_slug: "optiver", ats: "greenhouse", board_token: "optiverus", careers_url: "https://www.optiver.com/working-at-optiver/career-opportunities" },
  { company: "Virtu Financial", company_slug: "virtu", ats: "greenhouse", board_token: "virtu", careers_url: "https://www.virtu.com/careers" },
  { company: "Point72", company_slug: "point72", ats: "greenhouse", board_token: "point72", careers_url: "https://careers.point72.com" },
  { company: "IMC", company_slug: "imc", ats: "greenhouse", board_token: "imc", careers_url: "https://www.imc.com/us/careers" },
  { company: "DRW", company_slug: "drw", ats: "greenhouse", board_token: "drweng", careers_url: "https://www.drw.com/careers" },
  { company: "Oscar Health", company_slug: "oscar", ats: "greenhouse", board_token: "oscar", careers_url: "https://www.hioscar.com/careers" },
  { company: "SoFi", company_slug: "sofi", ats: "greenhouse", board_token: "sofi", careers_url: "https://www.sofi.com/careers" },
  { company: "Waymo", company_slug: "waymo", ats: "greenhouse", board_token: "waymo", careers_url: "https://waymo.com/careers" },
  { company: "Toast", company_slug: "toast", ats: "greenhouse", board_token: "toast", careers_url: "https://careers.toasttab.com" },
  { company: "Mercury", company_slug: "mercury", ats: "greenhouse", board_token: "mercury", careers_url: "https://mercury.com/jobs" },
  { company: "Checkr", company_slug: "checkr", ats: "greenhouse", board_token: "checkr", careers_url: "https://checkr.com/company/careers" },
  { company: "Akuna Capital", company_slug: "akuna", ats: "greenhouse", board_token: "akunacapital", careers_url: "https://www.akunacapital.com/careers" },
  { company: "Five Rings", company_slug: "fiverings", ats: "greenhouse", board_token: "fiveringsllc", careers_url: "https://www.fiverings.com/careers" },
  { company: "Flow Traders", company_slug: "flowtraders", ats: "greenhouse", board_token: "flowtraders", careers_url: "https://www.flowtraders.com/careers" },
];
